/**
 * Patrons feature – Display and manage Patrons (Cosmic, Terrestrial, and Trusts)
 *
 * Data paths:
 *   cosmic:   /data/patrons/{id}.json  (with manifest.json generated by build script)
 *   terrestrial: /data/terrestrial/{id}.json (fallback to /data/factions/{id}.json)
 *   religions: /data/religions/{id}.json
 *
 * All data is discovered via a manifest.json file that is generated automatically.
 * If manifest is missing, falls back to hardcoded known slugs.
 *
 * Patron JSON Structure (v2):
 *   - id, type, title, subtitle, version, tags
 *   - lore: { description, followers, names_across_regions, quote, signs, quotes }
 *   - domain_focus: string[]
 *   - runekeeper_options: { thiasos: { description, care }, codex: { description, upkeep } }
 *   - patrons_gift: { name, description, effect, cost }
 *   - rites: [{ name, tier, xp, action, range, resist, tags, materials, effect, push_it, cost, requires, invoke, duration, timer, integrity_timer }]
 *   - cantors_and_cults: { cantors: { name, description }, cult: { name, description } }
 *   - witchcraft: { name, description, color, lore, signature_rite, quote, tools: { ... }, hedge_gifts: [{ name, xp, description }] }
 *   - monastic_tradition: { name, description, color, quote, prerequisites, debt_resistant_frame, techniques: { basic, advanced, master }, corruption: [] }
 *   - corruption: [{ tier, benefit, cost }]
 *   - playstyle_notes: { description, emphasizes: [] }
 *   - sample_adventure: { title, description, quote }
 *   - optional_campaign_arc: { title, description, signs, optimization_plague, clockwork_demon, gm_guidance }
 *   - temporary_anima_system: { title, description, core_principles, creation_procedure, effects, scars, clearing_obligation, artificer_talents, gm_guidance }
 *   - rivalries: [{ patron, description }]
 *   - _license: string */
 
import { getState, saveState } from '../../core/state.js';
import { showToast } from '../../components/Toast.js';
import { escHtml } from '../../core/utils.js';
// ─── Import shared discovery ────────────────────────────
import { discoverPatrons } from '../../core/discovery.js';
 
// ============================================================
// CONSTANTS
// ============================================================
 
const COSMIC_DATA_PATH = './data/patrons/';
const TERRESTRIAL_DATA_PATH = './data/terrestrial/';
const TERRESTRIAL_FALLBACK_DATA_PATH = './data/factions/';
const RELIGION_DATA_PATH = './data/religions/';

// Bump this whenever the on-disk patron JSON schema changes in a way that
// would make a previously-cached copy of `state.patrons` stale or wrong
// (e.g. the rite tier vocabulary moving from Basic/Advanced/Master to
// Low/Standard/High). Any cached blob written under an older version is
// treated as invalid and force-reloaded from disk automatically, so this
// class of "stale cache silently hides new data forever" bug can't recur
// just because someone forgot to click Refresh.
const PATRON_SCHEMA_VERSION = 2;
 
// ============================================================
// DEFAULT DATA (fallback)
// ============================================================
 
const DEFAULT_COSMIC_PATRONS = [
    {
        id: 'the-traveler',
        name: 'The Traveler',
        icon: '🚶',
        domain: 'Ways & Journeys',
        subtitle: 'Guide of the Lost',
        description: 'The Traveler is the eternal guide of the road, guardian of those who walk the paths between what is and what might be.',
        lore: 'The Traveler has no fixed form, but appears as a wanderer at every crossroads.',
        rites: [],
        source: 'default'
    },
    {
        id: 'oath-of-flame-light',
        name: 'Oath of Flame & Light',
        icon: '🔥',
        domain: 'Dawn & Vows',
        subtitle: 'The Unquenchable Fire',
        description: 'The Oath of Flame & Light demands that those who swear within its radiance speak truly and pay the cost of keeping their word.',
        lore: 'Born from the first dawn fire, this patron is invoked by paladins and healers.',
        rites: [],
        source: 'default'
    }
];
 
const DEFAULT_TERRESTRIAL_PATRONS = [
    {
        id: 'velvet-court',
        name: 'The Velvet Court',
        icon: '🎭',
        type: 'Crime Syndicate',
        tier: 'II',
        description: 'A shadowy network of smugglers and information brokers operating in Silkstrand.',
        location: 'Silkstrand',
        leverage: 'Smuggling routes, information, forgery',
        debtTrigger: 'When Obligation fills, they demand a heist or assassination.',
        quirk: 'Every member wears a velvet glove on their left hand.',
        assetSlots: 4,
        maxAssetTier: 'Standard',
        obligationCapacity: 'Spirit+Presence+2',
        keyNPCs: ['Madam Serafine', 'Old Kes', 'Sister Agatha'],
        hooks: ['A rival faction is moving into the Dye District'],
        agendaTimer: { segments: 6, current: 2 },
        source: 'default'
    },
    {
        id: 'house-contarini',
        name: 'House Contarini',
        icon: '🏛️',
        type: 'Noble House',
        tier: 'II',
        description: 'A powerful Vilikari family with deep connections in the Archivolt and trade networks.',
        location: 'Vilikari Marches',
        leverage: 'Legal influence, grain contracts, safe passage',
        debtTrigger: 'When Obligation fills, they demand a political favor or a sealed document.',
        quirk: 'Their seal is a cracked marble column.',
        assetSlots: 4,
        maxAssetTier: 'Standard',
        obligationCapacity: 'Spirit+Presence+1',
        keyNPCs: ['Tema', 'Factor Voss'],
        hooks: ['A rival house is undercutting their prices'],
        agendaTimer: { segments: 8, current: 3 },
        source: 'default'
    }
];
 
const DEFAULT_TRUSTS = [
    {
        id: 'velvet-coin-trust',
        name: 'The Silk Coin',
        icon: '🪙',
        tier: 'I',
        description: 'A thieves\' guild operating in the shadows of Silkstrand.',
        maxAssets: 2,
        maxAssetTier: 'Standard',
        assets: [],
        followers: [],
        obligation: 0,
        capacity: 4,
        source: 'default'
    }
];
 
const DEFAULT_RELIGIONS = [
    {
        id: 'everflame',
        name: 'The Everflame',
        icon: '🔥',
        description: 'The state religion of Ecktoria, born from the imperial forge.',
        lore: 'The Everflame began as a cult of the imperial forge.',
        doctrines: ['The flame witnesses all.', 'Confession must be public.'],
        practices: ['The Candle Test', 'The Unspoken Ninth Citation'],
        orders: [
            { id: 'oath_of_flame__light', name: 'Oath of Flame & Light', role: 'Warriors and crusaders' }
        ],
        source: 'default'
    }
];
 
// ============================================================
// HELPERS
// ============================================================
 
function safeString(val) {
    if (val === undefined || val === null) return '';
    if (typeof val === 'string') return val;
    if (typeof val === 'number' || typeof val === 'boolean') return String(val);
    if (Array.isArray(val)) return val.map(v => safeString(v)).join(', ');
    if (typeof val === 'object') {
        if (val.name) return safeString(val.name);
        if (val.label) return safeString(val.label);
        if (val.description) return safeString(val.description);
        if (val.lore) return safeString(val.lore);
        if (val.effect) return safeString(val.effect);
        if (val.text) return safeString(val.text);
        if (val.quote) return safeString(val.quote);
        try { return JSON.stringify(val); } catch (e) { return '[object]'; }
    }
    return String(val);
}
 
function getPatronDescription(patron) {
    if (!patron) return 'No description available.';
 
    // Try the lore.description field first (new format)
    if (patron.lore?.description) return patron.lore.description;
 
    // Fallback to old format
    if (typeof patron.description === 'string') return patron.description;
    if (patron.description?.description) return patron.description.description;
    if (patron.description?.lore) return patron.description.lore;
 
    // Last resort
    if (typeof patron.lore === 'string') return patron.lore;
    return safeString(patron.description) || 'No description available.';
}
 
function getPatronLore(patron) {
    if (!patron?.lore) return null;
    return patron.lore;
}
 
function getPatronSummary(patron) {
    if (!patron) return '';
    if (patron.subtitle && typeof patron.subtitle === 'string') return patron.subtitle;
    if (patron.domain && typeof patron.domain === 'string') return patron.domain;
    if (patron.type && typeof patron.type === 'string') return patron.type;
    if (patron.agenda && typeof patron.agenda === 'string') return patron.agenda;
    const desc = getPatronDescription(patron);
    const firstSentence = desc.split('.')[0] || desc;
    return firstSentence.substring(0, 80) + (firstSentence.length > 80 ? '...' : '');
}
 
function getPatronIcon(patron) {
    if (patron?.icon) return patron.icon;
    return '🌟';
}
 
function getPatronColor(patron) {
    if (patron?.color) return patron.color;
    if (patron?.witchcraft?.color) return patron.witchcraft.color;
    if (patron?.monastic_tradition?.color) return patron.monastic_tradition.color;
    return 'var(--gold)';
}
 
function normalizePatron(p) {
    if (!p) return p;
    const result = { ...p };
    if (!result.name && result.title) result.name = result.title;
    if (!result.domain && result.subtitle) result.domain = result.subtitle;
    if (result.description && typeof result.description === 'object') {
        if (result.description.description) {
            result._rawDescription = result.description;
            result.description = result.description.description;
        }
    }
    // Ensure rites are objects
    if (result.rites && Array.isArray(result.rites)) {
        result.rites = result.rites.map(r => {
            if (typeof r === 'string') {
                return { name: r, tier: 'Basic', xp: 4, effect: r };
            }
            return r;
        });
    }
    return result;
}
 
function formatText(text) {
    if (!text) return '';
    return escHtml(text).replace(/\n/g, '<br>');
}
 
function sortByName(a, b) {
    const nameA = (a.name || a.title || '').toLowerCase();
    const nameB = (b.name || b.title || '').toLowerCase();
    return nameA.localeCompare(nameB);
}
 
function getTierColor(tier) {
    const colors = {
        'Cantrip': 'var(--text3)',
        'Basic': '#6baa7a',
        'Low': '#6baa7a',
        'Standard': '#d4af37',
        'Advanced': '#c47a7a',
        'Master': '#b84a8a',
        'Epic': '#d94a4a',
        'High': '#8e44ad'
    };
    return colors[tier] || 'var(--text2)';
}
 
// ============================================================
// STATE
// ============================================================
 
let container = null;
const state = {
    cosmicPatrons: [],
    terrestrialPatrons: [],
    trusts: [],
    religions: [],
    selectedPatron: null,
    selectedTrust: null,
    selectedAsset: null,
    selectedReligion: null,
    viewMode: 'cosmic',
    isLoading: false,
    dataLoaded: false,
    usingFallback: false,
    obligation: {},
    expandedRites: new Set(),
    expandedSections: new Set()
};
 
// ============================================================
// LOAD DATA
// ============================================================
 
export async function loadPatronData(force = false) {
    const saved = getState();
    const cacheMatchesCurrentSchema = saved.patrons?._schemaVersion === PATRON_SCHEMA_VERSION;

    if (!force && saved.patrons && cacheMatchesCurrentSchema) {
        if (saved.patrons.cosmic?.length || saved.patrons.terrestrial?.length) {
            state.cosmicPatrons = (saved.patrons.cosmic || []).map(normalizePatron).sort(sortByName);
            state.terrestrialPatrons = (saved.patrons.terrestrial || []).map(normalizePatron).sort(sortByName);
            state.trusts = (saved.patrons.trusts || []).sort(sortByName);
            state.religions = (saved.patrons.religions || []).sort(sortByName);
            state.obligation = saved.patrons.obligation || {};
            console.log(`📦 Loaded from state: ${state.cosmicPatrons.length} cosmic, ${state.terrestrialPatrons.length} terrestrial, ${state.religions.length} religions`);
            state.dataLoaded = true;
            state.usingFallback = false;
            return;
        }
    }

    if (saved.patrons && !cacheMatchesCurrentSchema) {
        console.log(`📦 Cached patron data is schema v${saved.patrons._schemaVersion ?? 'unknown'}, current is v${PATRON_SCHEMA_VERSION} — reloading from disk.`);
    }

    await loadRemotePatrons();
}
 
async function loadRemotePatrons() {
    if (state.isLoading) return;
    state.isLoading = true;
 
    try {
        const cosmicSlugs = await discoverPatrons('cosmic', COSMIC_DATA_PATH);
        const terrestrialSlugs = await discoverPatrons('terrestrial', TERRESTRIAL_DATA_PATH, TERRESTRIAL_FALLBACK_DATA_PATH);
        const religionSlugs = await discoverPatrons('religion', RELIGION_DATA_PATH);
 
        // Fetch cosmic
        let cosmicPatrons = [];
        for (const slug of cosmicSlugs) {
            try {
                const res = await fetch(`${COSMIC_DATA_PATH}${slug}.json`);
                if (res.ok) {
                    const data = await res.json();
                    if (!data.id) data.id = slug;
                    // Normalize ID: replace underscores with hyphens to match expected format (e.g., defaults)
                    const normalizedId = data.id.replace(/_/g, '-');
                    data.id = normalizedId;
                    cosmicPatrons.push(normalizePatron(data));
                }
            } catch (e) { /* ignore */ }
        }
        if (cosmicPatrons.length === 0) {
            cosmicPatrons = DEFAULT_COSMIC_PATRONS.map(normalizePatron);
            state.usingFallback = true;
            showToast('⚠️ No cosmic patron files found. Using defaults.', 'warning');
        }
        state.cosmicPatrons = cosmicPatrons.sort(sortByName);
 
        // Fetch terrestrial
        let terrestrialPatrons = [];
        for (const slug of terrestrialSlugs) {
            try {
                let res = await fetch(`${TERRESTRIAL_DATA_PATH}${slug}.json`);
                if (!res.ok) {
                    res = await fetch(`${TERRESTRIAL_FALLBACK_DATA_PATH}${slug}.json`);
                }
                if (res.ok) {
                    const data = await res.json();
                    if (!data.id) data.id = slug;
                    // Normalize ID: replace underscores with hyphens to match expected format (e.g., defaults)
                    const normalizedId = data.id.replace(/_/g, '-');
                    data.id = normalizedId;
                    terrestrialPatrons.push(normalizePatron(data));
                }
            } catch (e) { /* ignore */ }
        }
        if (terrestrialPatrons.length === 0) {
            terrestrialPatrons = DEFAULT_TERRESTRIAL_PATRONS.map(normalizePatron);
            state.usingFallback = true;
            showToast('⚠️ No terrestrial patron files found. Using defaults.', 'warning');
        }
        state.terrestrialPatrons = terrestrialPatrons.sort(sortByName);
 
        // Fetch religions
        let religions = [];
        for (const slug of religionSlugs) {
            try {
                const res = await fetch(`${RELIGION_DATA_PATH}${slug}.json`);
                if (res.ok) {
                    const data = await res.json();
                    if (!data.id) data.id = slug;
                    // Normalize ID: replace underscores with hyphens to match expected format (e.g., defaults)
                    const normalizedId = data.id.replace(/_/g, '-');
                    data.id = normalizedId;
                    religions.push(data);
                }
            } catch (e) { /* ignore */ }
        }
        if (religions.length === 0) {
            religions = DEFAULT_RELIGIONS;
            state.usingFallback = true;
            showToast('⚠️ No religion files found. Using defaults.', 'warning');
        }
        state.religions = religions.sort(sortByName);
 
        if (state.trusts.length === 0) {
            state.trusts = DEFAULT_TRUSTS.sort(sortByName);
        } else {
            state.trusts.sort(sortByName);
        }
 
        state.dataLoaded = true;
        savePatronData();
 
    } catch (error) {
        console.warn('Failed to load remote patrons:', error);
        loadDefaultPatrons();
        showToast('⚠️ Error loading patrons. Using defaults.', 'error');
    } finally {
        state.isLoading = false;
    }
}
 
function loadDefaultPatrons() {
    state.cosmicPatrons = DEFAULT_COSMIC_PATRONS.map(normalizePatron).sort(sortByName);
    state.terrestrialPatrons = DEFAULT_TERRESTRIAL_PATRONS.map(normalizePatron).sort(sortByName);
    state.trusts = DEFAULT_TRUSTS.sort(sortByName);
    state.religions = DEFAULT_RELIGIONS.sort(sortByName);
    state.dataLoaded = true;
    state.usingFallback = true;
    console.log(`📦 Using defaults: ${state.cosmicPatrons.length} cosmic, ${state.terrestrialPatrons.length} terrestrial, ${state.religions.length} religions`);
}
 
function savePatronData() {
    const saved = getState();
    if (!saved.patrons) saved.patrons = {};
    saved.patrons.cosmic = state.cosmicPatrons;
    saved.patrons.terrestrial = state.terrestrialPatrons;
    saved.patrons.trusts = state.trusts;
    saved.patrons.religions = state.religions;
    saved.patrons.obligation = state.obligation;
    saved.patrons._schemaVersion = PATRON_SCHEMA_VERSION;
    saveState();
}
 
// ============================================================
// OBLIGATION MANAGEMENT
// ============================================================
 
export function getPatronObligation(characterId, patronId) {
    if (!state.obligation[characterId]) return 0;
    return state.obligation[characterId][patronId] || 0;
}
 
export function setPatronObligation(characterId, patronId, value) {
    if (!state.obligation[characterId]) state.obligation[characterId] = {};
    state.obligation[characterId][patronId] = Math.max(0, value);
    savePatronData();
}
 
export function addPatronObligation(characterId, patronId, amount = 1) {
    const current = getPatronObligation(characterId, patronId);
    setPatronObligation(characterId, patronId, current + amount);
}
 
export function clearPatronObligation(characterId, patronId, amount = 1) {
    const current = getPatronObligation(characterId, patronId);
    setPatronObligation(characterId, patronId, current - amount);
}
 
// ============================================================
// RENDER
// ============================================================
 
export function render(el) {
    container = el;
    loadPatronData();
 
    const usingFallback = state.usingFallback;
 
    container.innerHTML = `
        <div class="patrons-modern-layout">
            <header class="patrons-header" style="margin-bottom:0.5rem;">
                <h1 class="patrons-title">👁️ Patrons & Resources</h1>
                <p class="patrons-subtitle">Cosmic patrons, terrestrial powers, religions, and the assets they grant.</p>
                ${!state.dataLoaded ? '<p class="text-muted" style="font-size:0.85rem;">⏳ Loading data...</p>' : `<p class="text-muted" style="font-size:0.85rem;">📚 ${state.cosmicPatrons.length} cosmic, ${state.terrestrialPatrons.length} terrestrial, ${state.religions.length} religions</p>`}
                ${usingFallback ? `<div style="color:var(--warn);font-size:0.85rem;margin-top:0.3rem;">⚠️ Using fallback defaults for some data.</div>` : ''}
            </header>
 
            <div class="patrons-tabs" style="display:flex;gap:0.3rem;margin-bottom:0.5rem;flex-wrap:wrap;">
                <button class="patrons-tab active" data-view="cosmic">🌟 Cosmic</button>
                <button class="patrons-tab" data-view="terrestrial">🏛️ Terrestrial</button>
                <button class="patrons-tab" data-view="trusts">🤝 Trusts</button>
                <button class="patrons-tab" data-view="religions">⛪ Religions</button>
            </div>
 
            <div id="patrons-view-container" class="patrons-view-container">
                ${renderView('cosmic')}
            </div>
 
            <div id="patron-modal" class="patron-modal" style="display:none;"></div>
            <div id="asset-modal" class="patron-modal" style="display:none;"></div>
        </div>
    `;
 
    attachEvents();
}
 
function renderView(view) {
    state.viewMode = view;
    if (!state.dataLoaded) {
        return `<div class="patrons-empty"><div style="font-size:3rem;">⏳</div><div>Loading...</div></div>`;
    }
 
    switch(view) {
        case 'cosmic': return renderCosmicPatrons();
        case 'terrestrial': return renderTerrestrialPatrons();
        case 'trusts': return renderTrusts();
        case 'religions': return renderReligions();
        default: return renderCosmicPatrons();
    }
}
 
// ============================================================
// RENDER: COSMIC PATRONS
// ============================================================
 
function renderCosmicPatrons() {
    if (state.cosmicPatrons.length === 0) {
        return `
            <div class="patrons-empty">
                <div style="font-size:3rem;">🌟</div>
                <div>No cosmic patrons loaded.</div>
                <button class="btn btn-primary" onclick="window.loadDefaultPatrons()">📥 Load Defaults</button>
            </div>
        `;
    }
 
    const characterId = 'default-character';
    const obligationMap = state.obligation[characterId] || {};
 
    return `
        <div style="display:flex;flex-direction:column;gap:0.8rem;">
            <div class="patrons-scroll-grid" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:0.5rem;max-height:220px;overflow-y:auto;padding:0.2rem;border:1px solid var(--border);border-radius:var(--radius);background:var(--bg2);">
                ${state.cosmicPatrons.map(p => {
                    const obl = obligationMap[p.id] || 0;
                    const name = safeString(p.name || p.title || 'Unnamed');
                    const summary = getPatronSummary(p);
                    const icon = getPatronIcon(p);
                    const color = getPatronColor(p);
                    return `
                        <div class="patron-tile" onclick="window.viewPatron('${p.id}')" style="background:var(--bg3);border-radius:var(--radius);padding:0.3rem 0.5rem;cursor:pointer;display:flex;flex-direction:column;align-items:center;text-align:center;border-left:3px solid ${color};transition:all 0.2s;">
                            <div style="font-size:1.5rem;">${safeString(icon)}</div>
                            <div style="font-size:0.75rem;font-weight:600;color:var(--text);">${escHtml(name)}</div>
                            <div style="font-size:0.6rem;color:var(--text3);">${escHtml(summary)}</div>
                            <div style="font-size:0.55rem;color:var(--text2);margin-top:0.1rem;">Oblig: ${obl}</div>
                        </div>
                    `;
                }).join('')}
            </div>
 
            <div id="cosmic-description-area" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--gold);min-height:80px;">
                <p style="color:var(--text2);font-style:italic;margin:0;">Select a patron above to see their description and details.</p>
            </div>
 
            <div class="patrons-actions" style="display:flex;gap:0.3rem;flex-wrap:wrap;">
                <button class="btn btn-primary btn-sm" onclick="window.addCosmicPatron()">➕ Add Cosmic</button>
                <button class="btn btn-secondary btn-sm" onclick="window.refreshPatrons()">🔄 Refresh</button>
                <button class="btn btn-secondary btn-sm" onclick="window.loadDefaultPatrons()">📥 Load Defaults</button>
            </div>
        </div>
    `;
}
 
// ============================================================
// RENDER: TERRESTRIAL PATRONS
// ============================================================
 
function renderTerrestrialPatrons() {
    if (state.terrestrialPatrons.length === 0) {
        return `
            <div class="patrons-empty">
                <div style="font-size:3rem;">🏛️</div>
                <div>No terrestrial patrons loaded.</div>
                <button class="btn btn-primary" onclick="window.addTerrestrialPatron()">➕ Add Terrestrial</button>
                <button class="btn btn-secondary" onclick="window.loadDefaultPatrons()">📥 Load Defaults</button>
            </div>
        `;
    }
 
    return `
        <div style="display:flex;flex-direction:column;gap:0.8rem;">
            <div class="patrons-scroll-grid" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:0.5rem;max-height:220px;overflow-y:auto;padding:0.2rem;border:1px solid var(--border);border-radius:var(--radius);background:var(--bg2);">
                ${state.terrestrialPatrons.map(p => {
                    const name = safeString(p.name || p.title || 'Unnamed');
                    const summary = getPatronSummary(p);
                    const icon = getPatronIcon(p) || '🏛️';
                    const color = p.color || '#2980b9';
                    return `
                        <div class="patron-tile" onclick="window.viewTerrestrial('${p.id}')" style="background:var(--bg3);border-radius:var(--radius);padding:0.3rem 0.5rem;cursor:pointer;display:flex;flex-direction:column;align-items:center;text-align:center;border-left:3px solid ${color};transition:all 0.2s;">
                            <div style="font-size:1.5rem;">${safeString(icon)}</div>
                            <div style="font-size:0.75rem;font-weight:600;color:var(--text);">${escHtml(name)}</div>
                            <div style="font-size:0.6rem;color:var(--text3);">${escHtml(summary)}</div>
                            <div style="font-size:0.55rem;color:var(--text2);">Tier ${safeString(p.tier || 'I')}</div>
                        </div>
                    `;
                }).join('')}
            </div>
 
            <div id="terrestrial-description-area" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);min-height:80px;">
                <p style="color:var(--text2);font-style:italic;margin:0;">Select a terrestrial patron to see details.</p>
            </div>
 
            <div class="patrons-actions" style="display:flex;gap:0.3rem;flex-wrap:wrap;">
                <button class="btn btn-primary btn-sm" onclick="window.addTerrestrialPatron()">➕ Add Terrestrial</button>
                <button class="btn btn-secondary btn-sm" onclick="window.refreshPatrons()">🔄 Refresh</button>
            </div>
        </div>
    `;
}
 
// ============================================================
// RENDER: RELIGIONS
// ============================================================
 
function renderReligions() {
    if (state.religions.length === 0) {
        return `
            <div class="patrons-empty">
                <div style="font-size:3rem;">⛪</div>
                <div>No religions loaded.</div>
                <button class="btn btn-primary" onclick="window.addReligion()">➕ Add Religion</button>
            </div>
        `;
    }
 
    return `
        <div class="religions-grid" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:0.5rem;">
            ${state.religions.map(r => {
                const name = safeString(r.name || r.title || 'Unnamed');
                const orders = r.orders ? r.orders.length : 0;
                const icon = r.icon || '⛪';
                return `
                    <div class="religion-card" onclick="window.viewReligion('${r.id}')" style="background:var(--bg3);border-radius:var(--radius);padding:0.5rem;cursor:pointer;border-left:3px solid var(--gold);">
                        <div style="font-size:1.5rem;">${safeString(icon)}</div>
                        <div style="font-weight:600;">${escHtml(name)}</div>
                        <div style="font-size:0.7rem;color:var(--text3);">${orders} Orders</div>
                    </div>
                `;
            }).join('')}
        </div>
        <div class="patrons-actions" style="margin-top:0.5rem;">
            <button class="btn btn-primary" onclick="window.addReligion()">➕ Add Religion</button>
            <button class="btn btn-secondary" onclick="window.refreshPatrons()">🔄 Refresh</button>
        </div>
    `;
}
 
// ============================================================
// RENDER: TRUSTS
// ============================================================
 
function renderTrusts() {
    if (state.trusts.length === 0) {
        return `
            <div class="patrons-empty">
                <div style="font-size:3rem;">🤝</div>
                <div>No trusts created yet.</div>
                <button class="btn btn-primary" onclick="window.addTrust()">➕ Create Trust</button>
            </div>
        `;
    }
 
    return `
        <div class="trusts-grid" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:0.5rem;">
            ${state.trusts.map(t => {
                const name = safeString(t.name || t.title || 'Unnamed');
                const tier = safeString(t.tier || 'I');
                const icon = t.icon || '🤝';
                return `
                    <div class="trust-card" onclick="window.viewTrust('${t.id}')" style="background:var(--bg3);border-radius:var(--radius);padding:0.5rem;cursor:pointer;border-left:3px solid var(--gold);">
                        <div style="font-size:1.5rem;">${safeString(icon)}</div>
                        <div style="font-weight:600;">${escHtml(name)}</div>
                        <div style="font-size:0.7rem;color:var(--text3);">Tier ${escHtml(tier)}</div>
                    </div>
                `;
            }).join('')}
        </div>
        <div class="patrons-actions" style="margin-top:0.5rem;">
            <button class="btn btn-primary" onclick="window.addTrust()">➕ Create Trust</button>
            <button class="btn btn-secondary" onclick="window.refreshPatrons()">🔄 Refresh</button>
        </div>
    `;
}
 
// ============================================================
// PATRON DETAIL (Cosmic)
// ============================================================
 
function renderPatronDetail(patronId) {
    const patron = state.cosmicPatrons.find(p => p.id === patronId);
    if (!patron) {
        showToast('Patron not found', 'error');
        return;
    }
 
    const descArea = document.getElementById('cosmic-description-area');
    if (!descArea) return;
 
    const desc = getPatronDescription(patron);
    const name = safeString(patron.name || patron.title || 'Unnamed');
    const summary = getPatronSummary(patron);
    const icon = getPatronIcon(patron);
    const color = getPatronColor(patron);
 
    descArea.innerHTML = `
        <div style="display:flex;align-items:center;gap:0.5rem;flex-wrap:wrap;">
            <span style="font-size:1.5rem;">${safeString(icon)}</span>
            <span style="font-weight:600;font-size:1.1rem;">${escHtml(name)}</span>
            <span style="color:var(--text3);font-size:0.85rem;">${escHtml(summary)}</span>
            <span style="color:var(--text3);font-size:0.75rem;margin-left:auto;">Obligation: ${getPatronObligation('default-character', patron.id)}</span>
            <button class="btn btn-xs btn-primary" onclick="window.addPatronObligation('default-character', '${patron.id}', 1)">➕</button>
            <button class="btn btn-xs btn-secondary" onclick="window.clearPatronObligation('default-character', '${patron.id}', 1)">➖</button>
            <button class="btn btn-xs btn-ghost" onclick="window.openPatronDetailModal('${patron.id}')">📖 Full Details</button>
        </div>
        <div style="margin:0.3rem 0 0 0;color:var(--text2);font-size:0.9rem;line-height:1.5;overflow-y:auto;">
            ${formatText(desc)}
        </div>
    `;
}
 
// ============================================================
// RITE HELPERS & TOGGLE
// ============================================================
 
function riteHasDetails(r) {
    if (!r) return false;
    const hasMainText = safeString(r.effect || r.description || '').length > 0;
    const hasMeta = r.tier || r.xp || r.action || r.range || r.resist ||
        r.materials || r.cost || r.duration || r.invoke || r.requires ||
        r.push_it || r.timer || r.integrity_timer ||
        (r.tags && r.tags.length > 0);
    return hasMainText || hasMeta;
}
 
window.toggleRite = function(headerElement) {
    const item = headerElement.closest('.rite-item');
    if (!item) return;
    const details = item.querySelector('.rite-details');
    if (!details) return;
    const isExpanded = details.style.display !== 'none';
    details.style.display = isExpanded ? 'none' : 'block';
    const icon = item.querySelector('.rite-expand-icon');
    if (icon) icon.textContent = isExpanded ? '▸' : '▾';
    const riteId = item.dataset.riteId;
    if (riteId) {
        if (isExpanded) state.expandedRites.delete(riteId);
        else state.expandedRites.add(riteId);
    }
};
 
window.expandAllRites = function() {
    const modal = document.getElementById('patron-modal');
    if (!modal) return;
    modal.querySelectorAll('.rite-item.rite-expandable').forEach(item => {
        const details = item.querySelector('.rite-details');
        if (details) {
            details.style.display = 'block';
            const icon = item.querySelector('.rite-expand-icon');
            if (icon) icon.textContent = '▾';
            const riteId = item.dataset.riteId;
            if (riteId) state.expandedRites.add(riteId);
        }
    });
};
 
window.collapseAllRites = function() {
    const modal = document.getElementById('patron-modal');
    if (!modal) return;
    modal.querySelectorAll('.rite-item.rite-expandable').forEach(item => {
        const details = item.querySelector('.rite-details');
        if (details) {
            details.style.display = 'none';
            const icon = item.querySelector('.rite-expand-icon');
            if (icon) icon.textContent = '▸';
            const riteId = item.dataset.riteId;
            if (riteId) state.expandedRites.delete(riteId);
        }
    });
};
 
// ============================================================
// PATRON DETAIL MODAL (FULL)
// ============================================================
 
window.openPatronDetailModal = function(patronId) {
    const patron = state.cosmicPatrons.find(p => p.id === patronId);
    if (!patron) {
        showToast('Patron not found', 'error');
        return;
    }
 
    const modal = document.getElementById('patron-modal');
    modal.style.display = 'block';
 
    const name = safeString(patron.name || patron.title || 'Unnamed');
    const summary = getPatronSummary(patron);
    const desc = getPatronDescription(patron);
    const icon = getPatronIcon(patron);
    const color = getPatronColor(patron);
    const domain = safeString(patron.domain || patron.subtitle || 'Unknown Domain');
    const religion = safeString(patron.religion || '');
    const currentObligation = getPatronObligation('default-character', patron.id);
    const lore = getPatronLore(patron);
 
    // Build sections HTML
    const sectionsHtml = buildPatronSections(patron);
 
    modal.innerHTML = `
        <div class="modal-content patron-detail" style="width: 90%; max-width: 1200px; max-height: 90vh; overflow-y: auto; background:var(--bg1); padding:1.5rem; border-radius:var(--radius);">
            <button class="modal-close" onclick="window.closePatronModal()" style="float:right;background:none;border:none;font-size:1.5rem;cursor:pointer;color:var(--text3);">✕</button>
 
            <!-- Header -->
            <div class="patron-detail-header" style="display:flex;align-items:center;gap:1rem;margin-bottom:1rem;border-bottom:1px solid var(--border);padding-bottom:0.5rem;">
                <div class="patron-detail-icon" style="font-size:3rem;">${escHtml(icon)}</div>
                <div style="flex:1;">
                    <h2 style="margin:0;color:${color};">${escHtml(name)}</h2>
                    <div class="patron-detail-domain" style="color:var(--text2);font-size:1.1rem;">${escHtml(domain)}</div>
                    <div style="display:flex;gap:0.5rem;flex-wrap:wrap;margin-top:0.3rem;">
                        ${religion ? `<span class="badge badge-religion" style="background:${color};color:var(--bg);padding:0.1rem 0.5rem;border-radius:12px;font-size:0.8rem;">⛪ ${escHtml(religion)}</span>` : ''}
                        ${patron.tags && patron.tags.length > 0 ? patron.tags.slice(0, 5).map(t => `<span class="badge" style="background:var(--bg3);color:var(--text3);padding:0.05rem 0.4rem;border-radius:8px;font-size:0.65rem;">${escHtml(t)}</span>`).join('') : ''}
                        ${patron.source === 'default' ? '<span class="badge badge-remote" style="background:var(--bg3);color:var(--text3);padding:0.1rem 0.5rem;border-radius:12px;font-size:0.7rem;">📦 Default Data</span>' : ''}
                    </div>
                    <div style="margin-top:0.5rem;font-size:0.9rem;display:flex;gap:0.5rem;align-items:center;">
                        <span>Obligation: <strong>${currentObligation}</strong></span>
                        <button class="btn btn-xs btn-primary" onclick="window.addPatronObligation('default-character', '${patron.id}', 1)">➕</button>
                        <button class="btn btn-xs btn-secondary" onclick="window.clearPatronObligation('default-character', '${patron.id}', 1)">➖</button>
                    </div>
                </div>
            </div>
 
            <!-- Body -->
            <div class="patron-detail-body" style="display:flex;flex-direction:column;gap:0.8rem;">
                ${sectionsHtml}
            </div>
 
            <!-- Actions -->
            <div class="patron-detail-actions" style="display:flex;gap:0.5rem;margin-top:1rem;border-top:1px solid var(--border);padding-top:0.5rem;">
                <button class="btn btn-sm" onclick="window.editPatron('${patron.id}')">✏️ Edit</button>
                <button class="btn btn-sm btn-danger" onclick="window.deletePatron('${patron.id}')">🗑️ Delete</button>
                <button class="btn btn-sm btn-secondary" onclick="window.closePatronModal()">Close</button>
            </div>
        </div>
    `;
 
    modal.onclick = (e) => {
        if (e.target === modal) window.closePatronModal();
    };
};
 
// ============================================================
// BUILD PATRON SECTIONS
// ============================================================
 
function buildPatronSections(patron) {
    let html = '';
 
    // ─── Lore ──────────────────────────────────────────────────
    if (patron.lore) {
        const lore = patron.lore;
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--gold);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--gold);">📚 Lore</h3>
                ${lore.description ? `<p style="margin:0.3rem 0;white-space:pre-wrap;">${formatText(lore.description)}</p>` : ''}
                ${lore.followers ? `<p style="margin:0.3rem 0;white-space:pre-wrap;"><strong>Followers:</strong> ${formatText(lore.followers)}</p>` : ''}
                ${lore.quote ? `<blockquote style="margin:0.3rem 0;padding:0.5rem 1rem;background:var(--bg3);border-radius:var(--radius);border-left:4px solid var(--gold);"><em>${formatText(lore.quote)}</em></blockquote>` : ''}
                ${lore.names_across_regions ? `
                    <div style="margin:0.3rem 0;"><strong>Names Across Regions:</strong></div>
                    ${Object.entries(lore.names_across_regions).map(([region, name]) =>
                        `<div style="font-size:0.85rem;color:var(--text2);padding:0.1rem 0;">• <strong>${escHtml(region)}:</strong> ${formatText(name)}</div>`
                    ).join('')}
                ` : ''}
                ${lore.signs && lore.signs.length > 0 ? `
                    <div style="margin:0.3rem 0;"><strong>Signs:</strong></div>
                    <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                        ${lore.signs.map(s => `<li>${formatText(s)}</li>`).join('')}
                    </ul>
                ` : ''}
                ${lore.quotes && lore.quotes.length > 0 ? `
                    <div style="margin:0.3rem 0;"><strong>Quotes:</strong></div>
                    ${lore.quotes.map(q => `<blockquote style="margin:0.3rem 0;padding:0.3rem 0.8rem;background:var(--bg3);border-radius:var(--radius);border-left:3px solid var(--gold);font-size:0.85rem;">${formatText(q)}</blockquote>`).join('')}
                ` : ''}
            </div>
        `;
    }
 
    // ─── Domain Focus ──────────────────────────────────────────
    if (patron.domain_focus && patron.domain_focus.length > 0) {
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--gold);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--gold);">🎯 Domain Focus</h3>
                <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                    ${patron.domain_focus.map(d => `<li>${escHtml(safeString(d))}</li>`).join('')}
                </ul>
            </div>
        `;
    }
 
    // ─── Patron's Gift ─────────────────────────────────────────
    if (patron.patrons_gift) {
        const gift = patron.patrons_gift;
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--gold);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--gold);">🎁 Patron's Gift</h3>
                ${gift.name ? `<p style="margin:0.2rem 0;"><strong>${escHtml(gift.name)}</strong></p>` : ''}
                ${gift.description ? `<p style="margin:0.2rem 0;">${formatText(gift.description)}</p>` : ''}
                ${gift.effect ? `<p style="margin:0.2rem 0;"><strong>Effect:</strong> ${formatText(gift.effect)}</p>` : ''}
                ${gift.cost ? `<p style="margin:0.2rem 0;color:var(--text3);">Cost: ${formatText(gift.cost)}</p>` : ''}
            </div>
        `;
    }
 
    // ─── Rites ─────────────────────────────────────────────────
    if (patron.rites && patron.rites.length > 0) {
        const hasDetailedRites = typeof patron.rites[0] === 'object' && patron.rites[0].effect !== undefined;
        if (hasDetailedRites) {
            html += `
                <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--gold);">
                    <div style="display:flex;justify-content:space-between;align-items:center;margin:0 0 0.5rem 0;flex-wrap:wrap;gap:0.3rem;">
                        <h3 style="margin:0;color:var(--gold);">🔮 Rites (${patron.rites.length})</h3>
                        <div style="display:flex;gap:0.3rem;">
                            <button class="btn btn-xs btn-secondary" onclick="window.expandAllRites()">📖 Expand All</button>
                            <button class="btn btn-xs btn-secondary" onclick="window.collapseAllRites()">📕 Collapse All</button>
                        </div>
                    </div>
                    <div class="rites-list" style="display:flex;flex-direction:column;gap:0.5rem;">
                        ${patron.rites.map((r, idx) => {
                            const riteId = `${patron.id}-rite-${idx}`;
                            const isExpanded = state.expandedRites.has(riteId);
                            const hasDetails = riteHasDetails(r);
                            const riteName = safeString(r.name);
                            const riteTier = safeString(r.tier || '');
                            const riteMainText = safeString(r.effect || r.description || '');
                            const tierColor = getTierColor(riteTier);
 
                            let detailsHtml = '';
                            if (hasDetails) {
                                detailsHtml = `
                                    <div class="rite-details" style="margin-top:0.4rem;padding:0.5rem 0.8rem;background:var(--bg3);border-radius:var(--radius);${isExpanded ? '' : 'display:none;'}">
                                        ${riteMainText ? `<div class="rite-description" style="margin-bottom:0.4rem;line-height:1.5;">${formatText(riteMainText)}</div>` : ''}
                                        ${r.materials ? `<div class="rite-meta" style="font-size:0.85rem;color:var(--text2);margin-bottom:0.15rem;"><strong>📦 Materials:</strong> ${formatText(safeString(r.materials))}</div>` : ''}
                                        ${r.push_it ? `<div class="rite-meta" style="font-size:0.85rem;color:var(--text2);margin-bottom:0.15rem;"><strong>⚡ Push It:</strong> ${formatText(safeString(r.push_it))}</div>` : ''}
                                        <div style="display:flex;flex-wrap:wrap;gap:0.3rem 0.8rem;font-size:0.75rem;color:var(--text3);margin-top:0.15rem;">
                                            ${r.tier ? `<span><strong>Tier:</strong> ${escHtml(safeString(r.tier))}</span>` : ''}
                                            ${r.xp ? `<span><strong>XP:</strong> ${escHtml(safeString(r.xp))}</span>` : ''}
                                            ${r.action ? `<span><strong>Action:</strong> ${escHtml(safeString(r.action))}</span>` : ''}
                                            ${r.range ? `<span><strong>Range:</strong> ${escHtml(safeString(r.range))}</span>` : ''}
                                            ${r.resist ? `<span><strong>Resist:</strong> ${escHtml(safeString(r.resist))}</span>` : ''}
                                            ${r.invoke ? `<span><strong>Invoke:</strong> ${escHtml(safeString(r.invoke))}</span>` : ''}
                                            ${r.requires ? `<span><strong>Requires:</strong> ${formatText(safeString(r.requires))}</span>` : ''}
                                            ${r.cost ? `<span><strong>Cost:</strong> ${formatText(safeString(r.cost))}</span>` : ''}
                                            ${r.timer ? `<span><strong>Timer:</strong> ${escHtml(safeString(r.timer))}</span>` : ''}
                                            ${r.integrity_timer ? `<span><strong>Integrity Timer:</strong> ${escHtml(safeString(r.integrity_timer))}</span>` : ''}
                                        </div>
                                        ${r.tags && r.tags.length > 0 ? `
                                            <div class="rite-tags" style="display:flex;gap:0.2rem;flex-wrap:wrap;margin-top:0.2rem;">
                                                ${r.tags.map(t => `<span class="badge badge-tag" style="background:var(--bg2);padding:0.05rem 0.4rem;border-radius:8px;font-size:0.65rem;color:var(--text3);border:1px solid var(--border);">${escHtml(safeString(t))}</span>`).join('')}
                                            </div>
                                        ` : ''}
                                    </div>
                                `;
                            }
                            return `
                                <div class="rite-item ${hasDetails ? 'rite-expandable' : ''}" data-rite-id="${escHtml(riteId)}" style="background:var(--bg3);border-radius:var(--radius);padding:0.4rem 0.8rem;border-left:3px solid ${tierColor};">
                                    <div class="rite-header" ${hasDetails ? `onclick="window.toggleRite(this)"` : ''} style="display:flex;justify-content:space-between;align-items:center;cursor:${hasDetails ? 'pointer' : 'default'};">
                                        <span class="rite-name" style="font-weight:600;">${escHtml(riteName)}</span>
                                        <span style="display:flex;align-items:center;gap:0.5rem;">
                                            ${riteTier ? `<span class="rite-tier" style="font-size:0.75rem;color:${tierColor};font-weight:600;">${escHtml(riteTier)}</span>` : ''}
                                            ${r.xp ? `<span style="font-size:0.7rem;color:var(--text3);">${escHtml(safeString(r.xp))} XP</span>` : ''}
                                            ${hasDetails ? `<span class="rite-expand-icon" style="font-size:0.8rem;color:var(--text3);">${isExpanded ? '▾' : '▸'}</span>` : ''}
                                        </span>
                                    </div>
                                    ${detailsHtml}
                                </div>
                            `;
                        }).join('')}
                    </div>
                </div>
            `;
        } else {
            html += `
                <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--gold);">
                    <h3 style="margin:0 0 0.5rem 0;color:var(--gold);">🔮 Rites (${patron.rites.length})</h3>
                    <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                        ${patron.rites.map(r => `<li>${escHtml(safeString(r))}</li>`).join('')}
                    </ul>
                </div>
            `;
        }
    }
 
    // ─── Runekeeper Options ────────────────────────────────────
    if (patron.runekeeper_options) {
        const rko = patron.runekeeper_options;
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--gold);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--gold);">📜 Runekeeper Options</h3>
                ${rko.thiasos ? `
                    <div style="margin-bottom:0.5rem;">
                        <strong>🐾 Thiasos (Familiar):</strong>
                        <p style="margin:0.2rem 0;">${formatText(safeString(rko.thiasos.description))}</p>
                        ${rko.thiasos.care ? `<p style="margin:0.2rem 0;font-size:0.85rem;color:var(--text3);"><strong>Care:</strong> ${formatText(safeString(rko.thiasos.care))}</p>` : ''}
                    </div>
                ` : ''}
                ${rko.codex ? `
                    <div>
                        <strong>📖 Codex:</strong>
                        <p style="margin:0.2rem 0;">${formatText(safeString(rko.codex.description))}</p>
                        ${rko.codex.upkeep ? `<p style="margin:0.2rem 0;font-size:0.85rem;color:var(--text3);"><strong>Upkeep:</strong> ${formatText(safeString(rko.codex.upkeep))}</p>` : ''}
                    </div>
                ` : ''}
            </div>
        `;
    }
 
    // ─── Corruption ────────────────────────────────────────────
    if (patron.corruption && patron.corruption.length > 0) {
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--red);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--red);">⚠️ Corruption</h3>
                <table style="width:100%;border-collapse:collapse;font-size:0.85rem;">
                    <thead><tr style="border-bottom:2px solid var(--border);"><th style="text-align:left;padding:0.2rem 0.4rem;">Tier</th><th style="text-align:left;padding:0.2rem 0.4rem;">Benefit</th><th style="text-align:left;padding:0.2rem 0.4rem;">Cost / Quirk</th></tr></thead>
                    <tbody>${patron.corruption.map(c => `<tr style="border-bottom:1px solid var(--border);"><td style="padding:0.2rem 0.4rem;font-weight:600;">${escHtml(safeString(c.tier))}</td><td style="padding:0.2rem 0.4rem;color:var(--gold);">${escHtml(safeString(c.benefit))}</td><td style="padding:0.2rem 0.4rem;color:var(--red);">${escHtml(safeString(c.cost))}</td></tr>`).join('')}</tbody>
                </table>
            </div>
        `;
    }
 
    // ─── Witchcraft ────────────────────────────────────────────
    if (patron.witchcraft) {
        const wc = patron.witchcraft;
        const wcColor = wc.color || '#27ae60';
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid ${wcColor};">
                <h3 style="margin:0 0 0.3rem 0;color:${wcColor};">🧹 ${wc.name || 'Witchcraft'}</h3>
                ${wc.description ? `<p style="margin:0.2rem 0;">${formatText(wc.description)}</p>` : ''}
                ${wc.lore ? `<p style="margin:0.2rem 0;font-size:0.85rem;color:var(--text2);">${formatText(wc.lore)}</p>` : ''}
                ${wc.signature_rite ? `<p style="margin:0.2rem 0;"><strong>Signature Rite:</strong> ${escHtml(wc.signature_rite)}</p>` : ''}
                ${wc.quote ? `<blockquote style="margin:0.2rem 0;padding:0.3rem 0.8rem;background:var(--bg3);border-radius:var(--radius);border-left:3px solid ${wcColor};font-size:0.85rem;">${formatText(wc.quote)}</blockquote>` : ''}
                ${wc.tools ? `
                    <div style="margin:0.3rem 0;"><strong>🛠️ Tools:</strong></div>
                    ${Object.entries(wc.tools).map(([key, tool]) => `
                        <div style="margin:0.1rem 0;padding:0.2rem 0.5rem;background:var(--bg3);border-radius:var(--radius);">
                            <strong>${escHtml(tool.name || key)}</strong>
                            <p style="margin:0.1rem 0;font-size:0.85rem;color:var(--text2);">${formatText(tool.description)}</p>
                        </div>
                    `).join('')}
                ` : ''}
                ${wc.hedge_gifts && wc.hedge_gifts.length > 0 ? `
                    <div style="margin:0.3rem 0;"><strong>🌿 Hedge Gifts:</strong></div>
                    <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                        ${wc.hedge_gifts.map(g => `<li><strong>${escHtml(safeString(g.name))}</strong> (${escHtml(safeString(g.xp))} XP): ${formatText(safeString(g.description))}</li>`).join('')}
                    </ul>
                ` : ''}
            </div>
        `;
    }
 
    // ─── Monastic Tradition ────────────────────────────────────
    if (patron.monastic_tradition) {
        const mt = patron.monastic_tradition;
        const mtColor = mt.color || '#f39c12';
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid ${mtColor};">
                <h3 style="margin:0 0 0.3rem 0;color:${mtColor};">⛩️ ${mt.name || 'Monastic Tradition'}</h3>
                ${mt.description ? `<p style="margin:0.2rem 0;">${formatText(mt.description)}</p>` : ''}
                ${mt.quote ? `<blockquote style="margin:0.2rem 0;padding:0.3rem 0.8rem;background:var(--bg3);border-radius:var(--radius);border-left:3px solid ${mtColor};font-size:0.85rem;">${formatText(mt.quote)}</blockquote>` : ''}
                ${mt.prerequisites ? `<p style="margin:0.2rem 0;"><strong>Prerequisites:</strong> ${escHtml(mt.prerequisites)}</p>` : ''}
                ${mt.debt_resistant_frame ? `<p style="margin:0.2rem 0;color:var(--text2);">${formatText(mt.debt_resistant_frame)}</p>` : ''}
                ${mt.techniques ? `
                    <div style="margin:0.3rem 0;"><strong>Techniques:</strong></div>
                    ${['basic', 'advanced', 'master'].filter(l => mt.techniques[l]).map(level => {
                        const tech = mt.techniques[level];
                        const levelLabel = level.charAt(0).toUpperCase() + level.slice(1);
                        return `
                            <div style="margin:0.1rem 0;padding:0.2rem 0.5rem;background:var(--bg3);border-radius:var(--radius);border-left:2px solid ${mtColor};">
                                <strong>${levelLabel}: ${escHtml(tech.name)}</strong>
                                ${tech.xp ? `<span style="font-size:0.7rem;color:var(--text3);">(${tech.xp} XP)</span>` : ''}
                                <p style="margin:0.1rem 0;font-size:0.85rem;color:var(--text2);">${formatText(tech.description)}</p>
                                ${tech.cost ? `<p style="margin:0.1rem 0;font-size:0.75rem;color:var(--text3);"><strong>Cost:</strong> ${formatText(tech.cost)}</p>` : ''}
                                ${tech.prereq ? `<p style="margin:0.1rem 0;font-size:0.75rem;color:var(--text3);"><strong>Requirement:</strong> ${escHtml(tech.prereq)}</p>` : ''}
                            </div>
                        `;
                    }).join('')}
                ` : ''}
                ${mt.master_technique ? `
                    <div style="margin:0.3rem 0;padding:0.2rem 0.5rem;background:var(--bg3);border-radius:var(--radius);border-left:3px solid var(--gold);">
                        <strong>🏆 Master Technique: ${escHtml(mt.master_technique.name)}</strong>
                        ${mt.master_technique.xp ? `<span style="font-size:0.7rem;color:var(--text3);">(${mt.master_technique.xp} XP)</span>` : ''}
                        <p style="margin:0.1rem 0;font-size:0.85rem;color:var(--text2);">${formatText(mt.master_technique.description)}</p>
                        ${mt.master_technique.cost ? `<p style="margin:0.1rem 0;font-size:0.75rem;color:var(--text3);"><strong>Cost:</strong> ${formatText(mt.master_technique.cost)}</p>` : ''}
                    </div>
                ` : ''}
                ${mt.corruption && mt.corruption.length > 0 ? `
                    <div style="margin:0.3rem 0;"><strong>⚠️ Tradition Corruption:</strong></div>
                    <table style="width:100%;border-collapse:collapse;font-size:0.75rem;">
                        <thead><tr style="border-bottom:1px solid var(--border);"><th style="text-align:left;padding:0.1rem 0.3rem;">Tier</th><th style="text-align:left;padding:0.1rem 0.3rem;">Benefit</th><th style="text-align:left;padding:0.1rem 0.3rem;">Cost</th></tr></thead>
                        <tbody>${mt.corruption.map(c => `<tr style="border-bottom:1px solid var(--border);"><td style="padding:0.1rem 0.3rem;">${escHtml(safeString(c.tier))}</td><td style="padding:0.1rem 0.3rem;color:var(--gold);">${escHtml(safeString(c.benefit))}</td><td style="padding:0.1rem 0.3rem;color:var(--red);">${escHtml(safeString(c.cost))}</td></tr>`).join('')}</tbody>
                    </table>
                ` : ''}
            </div>
        `;
    }
 
    // ─── Cantors & Cults ──────────────────────────────────────
    if (patron.cantors_and_cults) {
        const cc = patron.cantors_and_cults;
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--gold);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--gold);">🎶 Cantors & Cults</h3>
                ${cc.cantors ? `
                    <div style="margin:0.2rem 0;">
                        <strong>🎵 ${cc.cantors.name || 'Cantors'}:</strong>
                        <p style="margin:0.1rem 0;">${formatText(safeString(cc.cantors.description))}</p>
                    </div>
                ` : ''}
                ${cc.cult ? `
                    <div style="margin:0.2rem 0;">
                        <strong>🏛️ ${cc.cult.name || 'Cult'}:</strong>
                        <p style="margin:0.1rem 0;">${formatText(safeString(cc.cult.description))}</p>
                    </div>
                ` : ''}
            </div>
        `;
    }
 
    // ─── Rivalries ─────────────────────────────────────────────
    if (patron.rivalries && patron.rivalries.length > 0) {
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--orange);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--orange);">⚔️ Rivalries</h3>
                ${patron.rivalries.map(r => `
                    <div style="margin:0.1rem 0;padding:0.2rem 0.5rem;background:var(--bg3);border-radius:var(--radius);">
                        <strong>${escHtml(safeString(r.patron))}</strong>
                        <p style="margin:0.1rem 0;font-size:0.85rem;color:var(--text2);">${formatText(r.description)}</p>
                    </div>
                `).join('')}
            </div>
        `;
    }
 
    // ─── Playstyle Notes ──────────────────────────────────────
    if (patron.playstyle_notes) {
        const pn = patron.playstyle_notes;
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--gold);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--gold);">🎮 Playstyle Notes</h3>
                ${pn.description ? `<p style="margin:0.2rem 0;">${formatText(pn.description)}</p>` : ''}
                ${pn.emphasizes && pn.emphasizes.length > 0 ? `
                    <div style="margin:0.2rem 0;"><strong>Emphasizes:</strong></div>
                    <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                        ${pn.emphasizes.map(e => `<li>${formatText(e)}</li>`).join('')}
                    </ul>
                ` : ''}
            </div>
        `;
    }
 
    // ─── Sample Adventure ─────────────────────────────────────
    if (patron.sample_adventure) {
        const sa = patron.sample_adventure;
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--gold);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--gold);">🎲 Sample Adventure</h3>
                ${sa.title ? `<p style="margin:0.2rem 0;"><strong>${escHtml(sa.title)}</strong></p>` : ''}
                ${sa.description ? `<p style="margin:0.2rem 0;">${formatText(sa.description)}</p>` : ''}
                ${sa.quote ? `<blockquote style="margin:0.2rem 0;padding:0.3rem 0.8rem;background:var(--bg3);border-radius:var(--radius);border-left:3px solid var(--gold);font-size:0.85rem;">${formatText(sa.quote)}</blockquote>` : ''}
            </div>
        `;
    }
 
    // ─── Optional Campaign Arc ────────────────────────────────
    if (patron.optional_campaign_arc) {
        const oca = patron.optional_campaign_arc;
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--purple);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--purple);">🌅 Optional Campaign Arc</h3>
                ${oca.title ? `<p style="margin:0.2rem 0;"><strong>${escHtml(oca.title)}</strong></p>` : ''}
                ${oca.description ? `<p style="margin:0.2rem 0;">${formatText(oca.description)}</p>` : ''}
                ${oca.signs && oca.signs.length > 0 ? `
                    <div style="margin:0.2rem 0;"><strong>Signs:</strong></div>
                    <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                        ${oca.signs.map(s => `<li>${formatText(s)}</li>`).join('')}
                    </ul>
                ` : ''}
                ${oca.gm_guidance ? `<p style="margin:0.2rem 0;font-size:0.85rem;color:var(--text2);"><strong>GM Guidance:</strong> ${formatText(oca.gm_guidance)}</p>` : ''}
            </div>
        `;
    }
 
    // ─── Temporary Anima System ───────────────────────────────
    if (patron.temporary_anima_system) {
        const tas = patron.temporary_anima_system;
        html += `
            <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);">
                <h3 style="margin:0 0 0.3rem 0;color:var(--blue);">⚡ Temporary Anima System</h3>
                ${tas.title ? `<p style="margin:0.2rem 0;"><strong>${escHtml(tas.title)}</strong></p>` : ''}
                ${tas.description ? `<p style="margin:0.2rem 0;">${formatText(tas.description)}</p>` : ''}
                ${tas.core_principles && tas.core_principles.length > 0 ? `
                    <div style="margin:0.2rem 0;"><strong>Core Principles:</strong></div>
                    <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                        ${tas.core_principles.map(p => `<li>${formatText(p)}</li>`).join('')}
                    </ul>
                ` : ''}
                ${tas.effects && tas.effects.length > 0 ? `
                    <div style="margin:0.2rem 0;"><strong>Effects:</strong></div>
                    <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                        ${tas.effects.map(e => `<li><strong>${escHtml(e.name)}</strong>: ${formatText(e.effect)}</li>`).join('')}
                    </ul>
                ` : ''}
            </div>
        `;
    }
 
    return html;
}
 
// ============================================================
// TERRESTRIAL PATRON DETAIL
// ============================================================
 
window.viewTerrestrial = function(id) {
    const patron = state.terrestrialPatrons.find(p => p.id === id);
    if (!patron) {
        showToast('Terrestrial patron not found', 'error');
        return;
    }
 
    const descArea = document.getElementById('terrestrial-description-area');
    if (descArea) {
        const desc = getPatronDescription(patron);
        const name = safeString(patron.name || patron.title || 'Unnamed');
        const summary = getPatronSummary(patron);
        const icon = getPatronIcon(patron) || '🏛️';
        descArea.innerHTML = `
            <div style="display:flex;align-items:center;gap:0.5rem;flex-wrap:wrap;">
                <span style="font-size:1.5rem;">${safeString(icon)}</span>
                <span style="font-weight:600;font-size:1.1rem;">${escHtml(name)}</span>
                <span style="color:var(--text3);font-size:0.85rem;">${escHtml(summary)}</span>
                <button class="btn btn-xs btn-ghost" onclick="window.openTerrestrialDetailModal('${patron.id}')" style="margin-left:auto;">📖 Full Details</button>
            </div>
            <div style="margin:0.3rem 0 0 0;color:var(--text2);font-size:0.9rem;line-height:1.5;overflow-y:auto;">
                ${formatText(desc)}
            </div>
        `;
    }
};
 
window.openTerrestrialDetailModal = function(id) {
    const patron = state.terrestrialPatrons.find(p => p.id === id);
    if (!patron) {
        showToast('Terrestrial patron not found', 'error');
        return;
    }
 
    const modal = document.getElementById('patron-modal');
    modal.style.display = 'block';
 
    const name = safeString(patron.name || patron.title || 'Unnamed');
    const desc = getPatronDescription(patron);
    const icon = getPatronIcon(patron) || '🏛️';
    const type = safeString(patron.type || patron.agenda || 'Terrestrial Patron');
    const tier = safeString(patron.tier || 'I');
 
    modal.innerHTML = `
        <div class="modal-content patron-detail" style="width: 90%; max-width: 800px; max-height: 90vh; overflow-y: auto; background:var(--bg1); padding:1.5rem; border-radius:var(--radius);">
            <button class="modal-close" onclick="window.closePatronModal()" style="float:right;background:none;border:none;font-size:1.5rem;cursor:pointer;color:var(--text3);">✕</button>
            <div class="patron-detail-header" style="display:flex;align-items:center;gap:1rem;margin-bottom:1rem;border-bottom:1px solid var(--border);padding-bottom:0.5rem;">
                <div style="font-size:3rem;">${escHtml(icon)}</div>
                <div>
                    <h2 style="margin:0;color:var(--gold);">${escHtml(name)}</h2>
                    <div style="color:var(--text2);">${escHtml(type)}</div>
                    <div style="color:var(--text3);">Tier ${escHtml(tier)}</div>
                </div>
            </div>
 
            <div class="patron-detail-body" style="display:flex;flex-direction:column;gap:0.8rem;">
                ${desc ? `
                    <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);">
                        <h3 style="margin:0 0 0.3rem 0;color:var(--blue);">📖 Description</h3>
                        <p style="margin:0;white-space:pre-wrap;">${formatText(desc)}</p>
                    </div>
                ` : ''}
                ${patron.location ? `
                    <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);">
                        <h3 style="margin:0 0 0.3rem 0;color:var(--blue);">📍 Location</h3>
                        <p style="margin:0;">${escHtml(patron.location)}</p>
                    </div>
                ` : ''}
                ${patron.leverage ? `
                    <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);">
                        <h3 style="margin:0 0 0.3rem 0;color:var(--blue);">💰 Leverage</h3>
                        <p style="margin:0;">${escHtml(patron.leverage)}</p>
                    </div>
                ` : ''}
                ${patron.debtTrigger ? `
                    <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);">
                        <h3 style="margin:0 0 0.3rem 0;color:var(--blue);">⚡ Debt Trigger</h3>
                        <p style="margin:0;">${escHtml(patron.debtTrigger)}</p>
                    </div>
                ` : ''}
                ${patron.quirk ? `
                    <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);">
                        <h3 style="margin:0 0 0.3rem 0;color:var(--blue);">🌀 Quirk</h3>
                        <p style="margin:0;">${escHtml(patron.quirk)}</p>
                    </div>
                ` : ''}
                <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);">
                    <h3 style="margin:0 0 0.3rem 0;color:var(--blue);">📊 Stats</h3>
                    <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                        <li>Asset Slots: ${escHtml(patron.assetSlots || 0)}</li>
                        <li>Max Asset Tier: ${escHtml(patron.maxAssetTier || 'Minor')}</li>
                        <li>Obligation Capacity: ${escHtml(patron.obligationCapacity || 'Spirit+Presence')}</li>
                    </ul>
                </div>
                ${patron.agendaTimer ? `
                    <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);">
                        <h3 style="margin:0 0 0.3rem 0;color:var(--blue);">⏱️ Agenda Timer</h3>
                        <div style="margin:0.3rem 0;">${safeString(patron.agendaTimer.current || 0)}/${safeString(patron.agendaTimer.segments || 6)}</div>
                        <div class="timer-bar" style="width:100%;height:6px;background:var(--bg3);border-radius:3px;overflow:hidden;">
                            <div class="timer-bar-fill" style="height:100%;width:${((patron.agendaTimer?.current||0)/(patron.agendaTimer?.segments||6))*100}%;background:var(--gold);"></div>
                        </div>
                    </div>
                ` : ''}
                ${patron.keyNPCs && patron.keyNPCs.length > 0 ? `
                    <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);">
                        <h3 style="margin:0 0 0.3rem 0;color:var(--blue);">👤 Key NPCs</h3>
                        <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                            ${patron.keyNPCs.map(n => `<li>${escHtml(safeString(n))}</li>`).join('')}
                        </ul>
                    </div>
                ` : ''}
                ${patron.hooks && patron.hooks.length > 0 ? `
                    <div class="patron-detail-section" style="background:var(--bg2);border-radius:var(--radius);padding:0.8rem;border-left:4px solid var(--blue);">
                        <h3 style="margin:0 0 0.3rem 0;color:var(--blue);">🔗 Hooks</h3>
                        <ul style="margin:0;padding-left:1.2rem;list-style-type:disc;">
                            ${patron.hooks.map(h => `<li>${escHtml(safeString(h))}</li>`).join('')}
                        </ul>
                    </div>
                ` : ''}
            </div>
 
            <div class="patron-detail-actions" style="display:flex;gap:0.5rem;margin-top:1rem;border-top:1px solid var(--border);padding-top:0.5rem;">
                <button class="btn btn-sm" onclick="window.editTerrestrial('${patron.id}')">✏️ Edit</button>
                <button class="btn btn-sm btn-danger" onclick="window.deleteTerrestrial('${patron.id}')">🗑️ Delete</button>
                <button class="btn btn-sm btn-secondary" onclick="window.closePatronModal()">Close</button>
            </div>
        </div>
    `;
 
    modal.onclick = (e) => {
        if (e.target === modal) window.closePatronModal();
    };
};
 
// ============================================================
// RELIGION & TRUST MODALS
// ============================================================
 
window.viewReligion = function(id) {
    const religion = state.religions.find(r => r.id === id);
    if (!religion) {
        showToast('Religion not found', 'error');
        return;
    }
    const modal = document.getElementById('patron-modal');
    modal.style.display = 'block';
    modal.innerHTML = `
        <div class="modal-content" style="width:90%;max-width:600px;max-height:90vh;overflow-y:auto;background:var(--bg1);padding:1.5rem;border-radius:var(--radius);">
            <button class="modal-close" onclick="window.closePatronModal()" style="float:right;background:none;border:none;font-size:1.5rem;cursor:pointer;color:var(--text3);">✕</button>
            <h2 style="color:var(--gold);">${escHtml(religion.name)}</h2>
            <div style="font-size:1.5rem;">${safeString(religion.icon || '⛪')}</div>
            ${religion.description ? `<p>${formatText(religion.description)}</p>` : ''}
            ${religion.lore ? `<p><strong>Lore:</strong> ${formatText(religion.lore)}</p>` : ''}
            ${religion.doctrines ? `<div><strong>Doctrines:</strong><ul>${religion.doctrines.map(d => `<li>${escHtml(d)}</li>`).join('')}</ul></div>` : ''}
            ${religion.practices ? `<div><strong>Practices:</strong><ul>${religion.practices.map(p => `<li>${escHtml(p)}</li>`).join('')}</ul></div>` : ''}
            ${religion.orders ? `<div><strong>Orders:</strong><ul>${religion.orders.map(o => `<li>${escHtml(o.name)} (${escHtml(o.role)})</li>`).join('')}</ul></div>` : ''}
            <button class="btn btn-sm btn-secondary" onclick="window.closePatronModal()" style="margin-top:0.5rem;">Close</button>
        </div>
    `;
    modal.onclick = (e) => {
        if (e.target === modal) window.closePatronModal();
    };
};
 
window.viewTrust = function(id) {
    const trust = state.trusts.find(t => t.id === id);
    if (!trust) {
        showToast('Trust not found', 'error');
        return;
    }
    const modal = document.getElementById('patron-modal');
    modal.style.display = 'block';
    modal.innerHTML = `
        <div class="modal-content" style="width:90%;max-width:600px;max-height:90vh;overflow-y:auto;background:var(--bg1);padding:1.5rem;border-radius:var(--radius);">
            <button class="modal-close" onclick="window.closePatronModal()" style="float:right;background:none;border:none;font-size:1.5rem;cursor:pointer;color:var(--text3);">✕</button>
            <h2 style="color:var(--gold);">${escHtml(trust.name)}</h2>
            <div style="font-size:1.5rem;">${safeString(trust.icon || '🤝')}</div>
            <div>Tier ${escHtml(trust.tier || 'I')}</div>
            ${trust.description ? `<p>${formatText(trust.description)}</p>` : ''}
            <div><strong>Obligation:</strong> ${trust.obligation || 0}/${trust.capacity || 4}</div>
            <div><strong>Assets:</strong> ${trust.assets?.length || 0}</div>
            <div><strong>Followers:</strong> ${trust.followers?.length || 0}</div>
            <button class="btn btn-sm btn-secondary" onclick="window.closePatronModal()" style="margin-top:0.5rem;">Close</button>
        </div>
    `;
    modal.onclick = (e) => {
        if (e.target === modal) window.closePatronModal();
    };
};
 
// ============================================================
// MODAL CONTROLS
// ============================================================
 
window.closePatronModal = function() {
    document.getElementById('patron-modal').style.display = 'none';
};
 
window.closeAssetModal = function() {
    document.getElementById('asset-modal').style.display = 'none';
};
 
window.viewPatron = function(id) {
    renderPatronDetail(id);
    const modal = document.getElementById('patron-modal');
    if (modal && modal.style.display !== 'none') {
        window.openPatronDetailModal(id);
    }
};
 
// ============================================================
// OBLIGATION WINDOW FUNCTIONS
// ============================================================
 
window.addPatronObligation = function(characterId, patronId, amount = 1) {
    addPatronObligation(characterId, patronId, amount);
    const patron = state.cosmicPatrons.find(p => p.id === patronId);
    if (patron) renderPatronDetail(patronId);
    showToast(`Added ${amount} Obligation to ${patronId}`, 'success');
};
 
window.clearPatronObligation = function(characterId, patronId, amount = 1) {
    clearPatronObligation(characterId, patronId, amount);
    const patron = state.cosmicPatrons.find(p => p.id === patronId);
    if (patron) renderPatronDetail(patronId);
    showToast(`Cleared ${amount} Obligation from ${patronId}`, 'info');
};
 
// ============================================================
// CRUD OPERATIONS
// ============================================================
 
window.addCosmicPatron = function() {
    const name = prompt('Enter patron name:');
    if (!name) return;
    const domain = prompt('Enter patron domain:') || 'Unknown';
    const icon = prompt('Enter patron icon (emoji):') || '🌟';
 
    state.cosmicPatrons.push(normalizePatron({
        id: 'patron-' + Date.now(),
        name,
        domain,
        icon,
        description: prompt('Enter description:') || 'A cosmic patron of the Amaranthine.',
        rites: prompt('Enter rites (comma-separated):')?.split(',').map(s => s.trim()) || [],
        rivals: prompt('Enter rivals (comma-separated):')?.split(',').map(s => s.trim()) || [],
        sigil: prompt('Enter sigil description:') || 'Unknown',
        corruption: prompt('Enter corruption effect:') || 'None',
        source: 'local'
    }));
    state.cosmicPatrons.sort(sortByName);
    savePatronData();
    refreshView();
    showToast(`Added patron: ${name}`, 'success');
};
 
window.editPatron = function(id) {
    const patron = state.cosmicPatrons.find(p => p.id === id);
    if (!patron) return;
    const name = prompt('Enter patron name:', patron.name || patron.title);
    if (!name) return;
    patron.name = name;
    patron.title = name;
    patron.domain = prompt('Enter patron domain:', patron.domain || patron.subtitle) || patron.domain;
    patron.icon = prompt('Enter patron icon:', patron.icon) || patron.icon;
    patron.description = prompt('Enter description:', patron.description) || patron.description;
    patron.sigil = prompt('Enter sigil:', patron.sigil) || patron.sigil;
    patron.corruption = prompt('Enter corruption:', patron.corruption) || patron.corruption;
    patron.source = 'local';
    state.cosmicPatrons.sort(sortByName);
    savePatronData();
    refreshView();
    window.closePatronModal();
    showToast(`Updated patron: ${name}`, 'success');
};
 
window.deletePatron = function(id) {
    const patron = state.cosmicPatrons.find(p => p.id === id);
    if (!patron) return;
    if (!confirm(`Delete patron "${patron.name || patron.title}"?`)) return;
    state.cosmicPatrons = state.cosmicPatrons.filter(p => p.id !== id);
    state.cosmicPatrons.sort(sortByName);
    savePatronData();
    refreshView();
    window.closePatronModal();
    showToast(`Deleted patron: ${patron.name || patron.title}`, 'info');
};
 
window.addTerrestrialPatron = function() {
    const name = prompt('Enter terrestrial patron name:');
    if (!name) return;
 
    state.terrestrialPatrons.push(normalizePatron({
        id: 'terr-' + Date.now(),
        name,
        type: prompt('Enter type (creditor/fence/sanctuary/military/tribal):') || 'patron',
        tier: prompt('Enter tier (I-V):') || 'I',
        description: prompt('Enter description:') || 'A terrestrial patron of the Amaranthine.',
        location: prompt('Enter location:') || 'Unknown',
        leverage: prompt('Enter leverage:') || 'None listed',
        debtTrigger: prompt('Enter debt trigger:') || 'When Obligation fills, they call in a debt.',
        quirk: prompt('Enter quirk:') || '',
        assetSlots: parseInt(prompt('Enter asset slots:') || '2'),
        maxAssetTier: prompt('Enter max asset tier (Minor/Standard/Major):') || 'Minor',
        obligationCapacity: prompt('Enter obligation capacity (Spirit+Presence or fixed):') || 'Spirit+Presence',
        source: 'local'
    }));
    state.terrestrialPatrons.sort(sortByName);
    savePatronData();
    refreshView();
    showToast(`Added terrestrial patron: ${name}`, 'success');
};
 
window.editTerrestrial = function(id) {
    const patron = state.terrestrialPatrons.find(p => p.id === id);
    if (!patron) return;
    const name = prompt('Enter name:', patron.name || patron.title);
    if (!name) return;
    patron.name = name;
    patron.title = name;
    patron.type = prompt('Enter type:', patron.type) || patron.type;
    patron.tier = prompt('Enter tier:', patron.tier) || patron.tier;
    patron.description = prompt('Enter description:', patron.description) || patron.description;
    patron.location = prompt('Enter location:', patron.location) || patron.location;
    patron.leverage = prompt('Enter leverage:', patron.leverage) || patron.leverage;
    patron.debtTrigger = prompt('Enter debt trigger:', patron.debtTrigger) || patron.debtTrigger;
    patron.quirk = prompt('Enter quirk:') || patron.quirk;
    patron.assetSlots = parseInt(prompt('Enter asset slots:', patron.assetSlots) || '2');
    patron.maxAssetTier = prompt('Enter max asset tier:', patron.maxAssetTier) || patron.maxAssetTier;
    patron.obligationCapacity = prompt('Enter obligation capacity:', patron.obligationCapacity) || patron.obligationCapacity;
    patron.source = 'local';
    state.terrestrialPatrons.sort(sortByName);
    savePatronData();
    refreshView();
    window.closePatronModal();
    showToast(`Updated terrestrial patron: ${name}`, 'success');
};
 
window.deleteTerrestrial = function(id) {
    const patron = state.terrestrialPatrons.find(p => p.id === id);
    if (!patron) return;
    if (!confirm(`Delete terrestrial patron "${patron.name || patron.title}"?`)) return;
    state.terrestrialPatrons = state.terrestrialPatrons.filter(p => p.id !== id);
    state.terrestrialPatrons.sort(sortByName);
    savePatronData();
    refreshView();
    window.closePatronModal();
    showToast(`Deleted terrestrial patron: ${patron.name || patron.title}`, 'info');
};
 
window.addReligion = function() {
    const name = prompt('Enter religion name:');
    if (!name) return;
    const icon = prompt('Enter icon (emoji):') || '⛪';
 
    state.religions.push({
        id: 'religion-' + Date.now(),
        name,
        icon,
        description: prompt('Enter description:') || 'A religion of the Amaranthine.',
        lore: prompt('Enter lore:') || '',
        doctrines: prompt('Enter doctrines (comma-separated):')?.split(',').map(s => s.trim()) || [],
        practices: prompt('Enter practices (comma-separated):')?.split(',').map(s => s.trim()) || [],
        orders: [],
        source: 'local'
    });
    state.religions.sort(sortByName);
    savePatronData();
    refreshView();
    showToast(`Added religion: ${name}`, 'success');
};
 
window.editReligion = function(id) {
    const religion = state.religions.find(r => r.id === id);
    if (!religion) return;
    const name = prompt('Enter religion name:', religion.name);
    if (!name) return;
    religion.name = name;
    religion.icon = prompt('Enter icon:', religion.icon) || religion.icon;
    religion.description = prompt('Enter description:', religion.description) || religion.description;
    religion.lore = prompt('Enter lore:', religion.lore) || religion.lore;
    religion.doctrines = prompt('Enter doctrines (comma-separated):', religion.doctrines.join(','))?.split(',').map(s => s.trim()) || [];
    religion.practices = prompt('Enter practices (comma-separated):', religion.practices.join(','))?.split(',').map(s => s.trim()) || [];
    religion.source = 'local';
    state.religions.sort(sortByName);
    savePatronData();
    refreshView();
    window.closePatronModal();
    showToast(`Updated religion: ${name}`, 'success');
};
 
window.deleteReligion = function(id) {
    const religion = state.religions.find(r => r.id === id);
    if (!religion) return;
    if (!confirm(`Delete religion "${religion.name}"?`)) return;
    state.religions = state.religions.filter(r => r.id !== id);
    state.religions.sort(sortByName);
    savePatronData();
    refreshView();
    window.closePatronModal();
    showToast(`Deleted religion: ${religion.name}`, 'info');
};
 
window.addTrust = function() {
    const name = prompt('Enter trust name:');
    if (!name) return;
 
    state.trusts.push({
        id: 'trust-' + Date.now(),
        name,
        icon: prompt('Enter icon (emoji):') || '🤝',
        tier: prompt('Enter tier (I-III):') || 'I',
        description: prompt('Enter description:') || 'A player trust formed by the party.',
        maxAssets: parseInt(prompt('Enter max asset slots:') || '2'),
        maxAssetTier: prompt('Enter max asset tier (Minor/Standard/Major):') || 'Standard',
        assets: [],
        followers: [],
        obligation: 0,
        capacity: parseInt(prompt('Enter obligation capacity:') || '4'),
        source: 'local'
    });
    state.trusts.sort(sortByName);
    savePatronData();
    refreshView();
    showToast(`Created trust: ${name}`, 'success');
};
 
window.editTrust = function(id) {
    const trust = state.trusts.find(t => t.id === id);
    if (!trust) return;
    const name = prompt('Enter trust name:', trust.name);
    if (!name) return;
    trust.name = name;
    trust.icon = prompt('Enter icon:', trust.icon) || trust.icon;
    trust.tier = prompt('Enter tier:', trust.tier) || trust.tier;
    trust.description = prompt('Enter description:', trust.description) || trust.description;
    trust.maxAssets = parseInt(prompt('Enter max asset slots:', trust.maxAssets) || '2');
    trust.maxAssetTier = prompt('Enter max asset tier:', trust.maxAssetTier) || trust.maxAssetTier;
    trust.capacity = parseInt(prompt('Enter obligation capacity:', trust.capacity) || '4');
    trust.source = 'local';
    state.trusts.sort(sortByName);
    savePatronData();
    refreshView();
    window.closePatronModal();
    showToast(`Updated trust: ${name}`, 'success');
};
 
window.deleteTrust = function(id) {
    const trust = state.trusts.find(t => t.id === id);
    if (!trust) return;
    if (!confirm(`Delete trust "${trust.name}"?`)) return;
    state.trusts = state.trusts.filter(t => t.id !== id);
    state.trusts.sort(sortByName);
    savePatronData();
    refreshView();
    window.closePatronModal();
    showToast(`Deleted trust: ${trust.name}`, 'info');
};
 
// ============================================================
// REFRESH
// ============================================================
 
window.refreshPatrons = function() {
    localStorage.removeItem('fates-edge-patrons-cache-cosmic');
    localStorage.removeItem('fates-edge-patrons-cache-terrestrial');
    localStorage.removeItem('fates-edge-patrons-cache-religion');
 
    const saved = getState();
    if (saved.patrons) {
        delete saved.patrons.cosmic;
        delete saved.patrons.terrestrial;
        delete saved.patrons.religions;
        // NOTE: trusts are player-created and never fetched remotely, so
        // they must never be cleared here — doing so used to silently
        // delete every Trust the party had built the moment "Refresh" was
        // clicked (loadRemotePatrons repopulates an empty trusts array with
        // DEFAULT_TRUSTS). We deliberately leave saved.patrons.trusts alone.
        saveState();
    }
 
    state.cosmicPatrons = [];
    state.terrestrialPatrons = [];
    // state.trusts is intentionally left untouched (see note above).
    state.religions = [];
    state.dataLoaded = false;
    state.usingFallback = false;
 
    loadPatronData(true);
    refreshView();
    showToast('🔄 Patrons refreshed from disk', 'success');
};
 
window.loadDefaultPatrons = function() {
    loadDefaultPatrons();
    refreshView();
    showToast('Loaded default patrons', 'success');
};
 
// ============================================================
// VIEW MANAGEMENT
// ============================================================
 
function refreshView() {
    const container = document.getElementById('patrons-view-container');
    if (container) {
        container.innerHTML = renderView(state.viewMode);
    }
    attachEvents();
}
 
// ============================================================
// EVENT LISTENERS
// ============================================================
 
export function attachEvents() {
    document.querySelectorAll('.patrons-tab').forEach(tab => {
        tab.addEventListener('click', () => {
            document.querySelectorAll('.patrons-tab').forEach(t => t.classList.remove('active'));
            tab.classList.add('active');
            const view = tab.dataset.view;
            const container = document.getElementById('patrons-view-container');
            if (container) {
                container.innerHTML = renderView(view);
                attachEvents();
            }
        });
    });
}
 
// ============================================================
// LIFECYCLE METHODS
// ============================================================
 
export function onActivate() {
    console.log('[Patrons] Activated');
    if (!state.dataLoaded) {
        loadPatronData();
    }
    refreshView();
}
 
export function onDeactivate() {
    console.log('[Patrons] Deactivated');
}
 
export function refresh() {
    localStorage.removeItem('fates-edge-patrons-cache-cosmic');
    localStorage.removeItem('fates-edge-patrons-cache-terrestrial');
    localStorage.removeItem('fates-edge-patrons-cache-religion');
    loadPatronData(true);
    refreshView();
}
 
export function destroy() {
    container = null;
}
 
// ============================================================
// EXPORTS
// ============================================================
 
export default {
    render,
    destroy,
    onActivate,
    onDeactivate,
    refresh,
    loadPatronData,
    loadRemotePatrons,
    loadDefaultPatrons,
    savePatronData,
    getPatronObligation,
    setPatronObligation,
    addPatronObligation,
    clearPatronObligation
};