import { describe, it, assert } from '../runner.js';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

// Static-analysis accessibility regression checks. These are NOT a
// replacement for real axe-core/Lighthouse coverage (see ACCESSIBILITY.md's
// "Setting the stage" section for why axe-core doesn't fit this project's
// current DOM-shim-based test harness) — they're a cheap, zero-dependency
// guard against regressing the exact bugs the accessibility pass found and
// fixed: unlabeled range inputs, alt-less images, and sidebar tabs that
// silently lose their aria-controls wiring.
//
// These scan raw source text with regex, not a real HTML/JS parser. That's
// a deliberate tradeoff: it's fast, needs no new dependency, and is good
// enough for flat attribute checks on single tags. It will NOT catch
// attributes split unusually or generated by string concatenation instead
// of template-literal interpolation — false negatives are possible, false
// positives should not be (a genuinely-labeled tag will always match).

const __dirname = dirname(fileURLToPath(import.meta.url));
const WEB_CLIENT_ROOT = join(__dirname, '..', '..');
const JS_FEATURES_DIR = join(WEB_CLIENT_ROOT, 'js', 'features');
const INDEX_HTML = join(WEB_CLIENT_ROOT, 'index.html');

function walkJsFiles(dir, out = []) {
    for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        const st = statSync(full);
        if (st.isDirectory()) walkJsFiles(full, out);
        else if (entry.endsWith('.js')) out.push(full);
    }
    return out;
}

function findTags(source, tagRegex) {
    const found = [];
    let m;
    tagRegex.lastIndex = 0;
    while ((m = tagRegex.exec(source)) !== null) {
        found.push(m[0]);
    }
    return found;
}

function shortLabel(file, tag) {
    return `${relative(WEB_CLIENT_ROOT, file)}: ${tag.replace(/\s+/g, ' ').trim().slice(0, 140)}`;
}

describe('Accessibility lint: <input type="range"> has an accessible name', () => {
    it('every range slider in js/features has aria-label or aria-labelledby', () => {
        const files = walkJsFiles(JS_FEATURES_DIR);
        const rangeTagRe = /<input\b[^>]*?type="range"[^>]*?\/?>/gs;
        const offenders = [];
        for (const file of files) {
            const source = readFileSync(file, 'utf8');
            for (const tag of findTags(source, rangeTagRe)) {
                if (!/aria-label(ledby)?="/.test(tag)) {
                    offenders.push(shortLabel(file, tag));
                }
            }
        }
        assert(
            offenders.length === 0,
            `Range input(s) missing aria-label/aria-labelledby:\n  ${offenders.join('\n  ')}`
        );
    });
});

describe('Accessibility lint: <img> tags have an alt attribute', () => {
    it('every <img> in js/features and index.html has alt="" or a real alt value', () => {
        const files = [...walkJsFiles(JS_FEATURES_DIR), INDEX_HTML];
        const imgTagRe = /<img\b[^>]*?\/?>/gs;
        const offenders = [];
        for (const file of files) {
            const source = readFileSync(file, 'utf8');
            for (const tag of findTags(source, imgTagRe)) {
                // alt="" (empty) is intentionally valid — it marks a purely
                // decorative image whose meaning is already conveyed by
                // adjacent visible text (e.g. a name label next to an
                // avatar). Only a fully missing alt attribute is a bug.
                if (!/\balt="/.test(tag)) {
                    offenders.push(shortLabel(file, tag));
                }
            }
        }
        assert(
            offenders.length === 0,
            `Image(s) missing an alt attribute entirely:\n  ${offenders.join('\n  ')}`
        );
    });
});

describe('Accessibility lint: sidebar tabs stay wired to their panels', () => {
    it('every role="tab" button in index.html has aria-controls', () => {
        const source = readFileSync(INDEX_HTML, 'utf8');
        const tabButtonRe = /<button\b[^>]*?role="tab"[^>]*?>/gs;
        const offenders = findTags(source, tabButtonRe).filter(tag => !/aria-controls="/.test(tag));
        assert(
            offenders.length === 0,
            `Sidebar tab button(s) missing aria-controls:\n  ${offenders.map(t => shortLabel(INDEX_HTML, t)).join('\n  ')}`
        );
    });

    it('every role="tab" button in index.html participates in aria-selected via router.js', () => {
        // router.js's navigate() is what actually flips aria-selected at
        // runtime (see ACCESSIBILITY.md) — this just guards against that
        // wiring being deleted or renamed without anyone noticing.
        const routerSource = readFileSync(join(WEB_CLIENT_ROOT, 'js', 'router.js'), 'utf8');
        assert(
            /setAttribute\(\s*['"]aria-selected['"]/.test(routerSource),
            'router.js no longer sets aria-selected on navigation — sidebar tabs would silently stop announcing which tab is active'
        );
    });
});
