import { describe, it, assert } from '../runner.js';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

// Static-analysis accessibility regression checks. These are NOT a
// replacement for real axe-core/Lighthouse coverage (see ACCESSIBILITY.md's
// "Setting the stage" section for why axe-core doesn't fit this project's
// current DOM-shim-based test harness) — they're a cheap, zero-dependency
// guard against regressing the exact bugs the accessibility pass found and
// fixed: unlabeled range inputs, alt-less images, and sidebar tabs that
// silently lose their aria-controls wiring.
//
// These scan raw source text with regex, not a real HTML/JS parser. That's
// a deliberate tradeoff: it's fast, needs no new dependency, and is good
// enough for flat attribute checks on single tags. It will NOT catch
// attributes split unusually or generated by string concatenation instead
// of template-literal interpolation — false negatives are possible, false
// positives should not be (a genuinely-labeled tag will always match).

const __dirname = dirname(fileURLToPath(import.meta.url));
const WEB_CLIENT_ROOT = join(__dirname, '..', '..');
const WEB_CLIENT_JS = join(WEB_CLIENT_ROOT, 'js');
const JS_FEATURES_DIR = join(WEB_CLIENT_ROOT, 'js', 'features');
const INDEX_HTML = join(WEB_CLIENT_ROOT, 'index.html');

function walkJsFiles(dir, out = []) {
    for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        const st = statSync(full);
        if (st.isDirectory()) walkJsFiles(full, out);
        else if (entry.endsWith('.js')) out.push(full);
    }
    return out;
}

function findTags(source, tagRegex) {
    const found = [];
    let m;
    tagRegex.lastIndex = 0;
    while ((m = tagRegex.exec(source)) !== null) {
        found.push(m[0]);
    }
    return found;
}

function shortLabel(file, tag) {
    return `${relative(WEB_CLIENT_ROOT, file)}: ${tag.replace(/\s+/g, ' ').trim().slice(0, 140)}`;
}

describe('Accessibility lint: <input type="range"> has an accessible name', () => {
    it('every range slider in js/features has aria-label or aria-labelledby', () => {
        const files = walkJsFiles(JS_FEATURES_DIR);
        const rangeTagRe = /<input\b[^>]*?type="range"[^>]*?\/?>/gs;
        const offenders = [];
        for (const file of files) {
            const source = readFileSync(file, 'utf8');
            for (const tag of findTags(source, rangeTagRe)) {
                if (!/aria-label(ledby)?="/.test(tag)) {
                    offenders.push(shortLabel(file, tag));
                }
            }
        }
        assert(
            offenders.length === 0,
            `Range input(s) missing aria-label/aria-labelledby:\n  ${offenders.join('\n  ')}`
        );
    });
});

describe('Accessibility lint: <img> tags have an alt attribute', () => {
    it('every <img> in js/features and index.html has alt="" or a real alt value', () => {
        const files = [...walkJsFiles(JS_FEATURES_DIR), INDEX_HTML];
        const imgTagRe = /<img\b[^>]*?\/?>/gs;
        const offenders = [];
        for (const file of files) {
            const source = readFileSync(file, 'utf8');
            for (const tag of findTags(source, imgTagRe)) {
                // alt="" (empty) is intentionally valid — it marks a purely
                // decorative image whose meaning is already conveyed by
                // adjacent visible text (e.g. a name label next to an
                // avatar). Only a fully missing alt attribute is a bug.
                if (!/\balt="/.test(tag)) {
                    offenders.push(shortLabel(file, tag));
                }
            }
        }
        assert(
            offenders.length === 0,
            `Image(s) missing an alt attribute entirely:\n  ${offenders.join('\n  ')}`
        );
    });
});

describe('Accessibility lint: sidebar tabs stay wired to their panels', () => {
    it('every role="tab" button in index.html has aria-controls', () => {
        const source = readFileSync(INDEX_HTML, 'utf8');
        const tabButtonRe = /<button\b[^>]*?role="tab"[^>]*?>/gs;
        const offenders = findTags(source, tabButtonRe).filter(tag => !/aria-controls="/.test(tag));
        assert(
            offenders.length === 0,
            `Sidebar tab button(s) missing aria-controls:\n  ${offenders.map(t => shortLabel(INDEX_HTML, t)).join('\n  ')}`
        );
    });

    it('every role="tab" button in index.html participates in aria-selected via router.js', () => {
        // router.js's navigate() is what actually flips aria-selected at
        // runtime (see ACCESSIBILITY.md) — this just guards against that
        // wiring being deleted or renamed without anyone noticing.
        const routerSource = readFileSync(join(WEB_CLIENT_ROOT, 'js', 'router.js'), 'utf8');
        assert(
            /setAttribute\(\s*['"]aria-selected['"]/.test(routerSource),
            'router.js no longer sets aria-selected on navigation — sidebar tabs would silently stop announcing which tab is active'
        );
    });
});

describe('Accessibility lint: role="button" is not used on non-<button> elements', () => {
    it('no <div>/<span> in js/features or index.html carries role="button"', () => {
        // A real <button> gets keyboard activation (Enter/Space), focus
        // styling, and its accessible role for free. role="button" on a
        // <div>/<span> gets none of that automatically -- it needs a hand-
        // rolled tabindex + keydown handler to not be a keyboard trap, and
        // that's exactly the kind of thing that's easy to add once and
        // forget to maintain. Cheaper to just never do it in the first
        // place; this is a static-analysis guard against reintroducing it.
        const files = [...walkJsFiles(JS_FEATURES_DIR), INDEX_HTML];
        const roleButtonRe = /<(div|span)\b[^>]*?role="button"[^>]*?>/gs;
        const offenders = [];
        for (const file of files) {
            const source = readFileSync(file, 'utf8');
            for (const tag of findTags(source, roleButtonRe)) {
                offenders.push(shortLabel(file, tag));
            }
        }
        assert(
            offenders.length === 0,
            `role="button" found on a non-<button> element (use a real <button> instead):\n  ${offenders.join('\n  ')}`
        );
    });
});

describe('Accessibility lint: interactive elements have an accessible name', () => {
    it('no <button>/<a> in js/features or index.html is both empty and unlabeled', () => {
        // Flags only the unambiguous case: a <button>/<a> whose inner
        // content, after stripping comments, is empty or whitespace-only
        // AND contains no ${...} interpolation (which could render real
        // text at runtime this static check can't see) AND has no
        // aria-label/aria-labelledby on the opening tag. This is
        // deliberately conservative -- it will not catch every missing
        // accessible name (e.g. an interpolated value that's itself
        // always empty), but it will never flag a genuinely-labeled or
        // genuinely-text-bearing element.
        const files = [...walkJsFiles(JS_FEATURES_DIR), INDEX_HTML];
        const tagRe = /<(button|a)\b([^>]*)>([\s\S]*?)<\/\1>/g;
        const offenders = [];
        for (const file of files) {
            const source = readFileSync(file, 'utf8');
            let m;
            tagRe.lastIndex = 0;
            while ((m = tagRe.exec(source)) !== null) {
                const [full, , attrs, inner] = m;
                const hasLabel = /aria-label(ledby)?="/.test(attrs);
                const stripped = inner.replace(/<!--[\s\S]*?-->/g, '').trim();
                const hasInterpolation = stripped.includes('${');
                if (!hasLabel && !hasInterpolation && stripped === '') {
                    offenders.push(shortLabel(file, full.slice(0, 140)));
                }
            }
        }
        assert(
            offenders.length === 0,
            `Empty, unlabeled interactive element(s) (add text content or aria-label):\n  ${offenders.join('\n  ')}`
        );
    });
});

describe('Accessibility lint: no positive tabindex', () => {
    it('no element in js/features or index.html has tabindex > 0', () => {
        // tabindex="0" (join the natural tab order) and tabindex="-1"
        // (focusable via script only, not Tab) are both fine and used
        // deliberately elsewhere in this codebase (e.g. router.js's
        // focus-on-navigate). A positive tabindex reorders the whole
        // page's tab sequence around one element's guess at what should
        // come "first" -- almost always an antipattern that fights the
        // DOM's natural (and usually correct) source-order tab sequence.
        const files = [...walkJsFiles(JS_FEATURES_DIR), INDEX_HTML];
        const positiveTabindexRe = /tabindex="([1-9][0-9]*)"/g;
        const offenders = [];
        for (const file of files) {
            const source = readFileSync(file, 'utf8');
            let m;
            positiveTabindexRe.lastIndex = 0;
            while ((m = positiveTabindexRe.exec(source)) !== null) {
                offenders.push(`${relative(WEB_CLIENT_ROOT, file)}: tabindex="${m[1]}"`);
            }
        }
        assert(
            offenders.length === 0,
            `Positive tabindex found (use "0" or "-1" instead):\n  ${offenders.join('\n  ')}`
        );
    });
});

describe('Accessibility lint: route changes keep the document title in sync', () => {
    it('router.js still updates document.title on navigate()', () => {
        // Regression guard for the specific fix -- see ACCESSIBILITY.md.
        // A static <title> means a screen reader announces nothing useful
        // when a keyboard/AT user navigates between tabs in this SPA.
        const routerSource = readFileSync(join(WEB_CLIENT_ROOT, 'js', 'router.js'), 'utf8');
        assert(
            /document\.title\s*=/.test(routerSource),
            'router.js no longer sets document.title on navigation'
        );
    });
});

describe('Accessibility lint: live-announcer regions are present at parse time', () => {
    it('index.html hardcodes both #a11y-announcer and #a11y-announcer-urgent', () => {
        // Regression guard: these used to only exist via
        // a11y-announce.js's create-on-first-call fallback, which risks a
        // late-injected aria-live region going unnoticed by some screen
        // readers. Hardcoding them in the static HTML removes that race
        // entirely -- see ACCESSIBILITY.md and index.html's own comment
        // at these two elements.
        const source = readFileSync(INDEX_HTML, 'utf8');
        assert(
            /id="a11y-announcer"[^>]*aria-live="polite"|aria-live="polite"[^>]*id="a11y-announcer"/.test(source),
            'index.html no longer hardcodes #a11y-announcer (aria-live="polite")'
        );
        assert(
            /id="a11y-announcer-urgent"[^>]*aria-live="assertive"|aria-live="assertive"[^>]*id="a11y-announcer-urgent"/.test(source),
            'index.html no longer hardcodes #a11y-announcer-urgent (aria-live="assertive")'
        );
    });
});

describe('Accessibility lint: voice/media events reach the sr-only announcer', () => {
    it('media.js recording overlay announces start/stop and periodic elapsed time (visual-only overlay otherwise)', () => {
        const source = readFileSync(join(WEB_CLIENT_JS, 'core', 'media.js'), 'utf8');
        assert(
            /import\s*\{\s*announce\s*\}\s*from\s*['"]\.\/a11y-announce\.js['"]/.test(source),
            'media.js no longer imports announce() from core/a11y-announce.js'
        );
        assert(
            /announce\(/.test(source),
            'media.js no longer calls announce() -- the recording-status overlay is position:fixed/pointer-events:none with no ARIA, so screen-reader users depend entirely on this call to know a recording started, stopped, or is still going'
        );
    });

    it('vtt-connected.js announces voice call initiation, not just a toast', () => {
        const source = readFileSync(join(WEB_CLIENT_JS, 'features', 'vtt', 'vtt-connected.js'), 'utf8');
        assert(
            /initiateVoiceCall\([^)]*\);[\s\S]{0,400}announce\(/.test(source),
            'vtt-connected.js no longer calls announce() near initiateVoiceCall() -- a screen-reader user pressing the call button would only get the visible toast'
        );
    });

    it('the session recording buttons keep their aria-label (GM Tools)', () => {
        const source = readFileSync(join(WEB_CLIENT_JS, 'features', 'gm-tools', 'index.js'), 'utf8');
        assert(
            /id="session-record-btn"[^>]*aria-label="/.test(source),
            '#session-record-btn lost its aria-label'
        );
        assert(
            /id="session-stop-btn"[^>]*aria-label="/.test(source),
            '#session-stop-btn lost its aria-label'
        );
    });
});

describe('Accessibility lint: "Type to Speak" chat TTS stays wired', () => {
    it('vtt-core.js still speaks new chat messages when VTT_CONFIG.speakMessages is on', () => {
        // Regression guard for the deaf/mute-player TTS bridge: a typed chat
        // message should reach players who are listening (voice call) but
        // not reading chat, the same way a spoken message would. This
        // doesn't attempt to simulate speechSynthesis under the DOM-shim
        // test harness (see tests/support/dom-shim.js) -- it just guards
        // against the wiring being silently deleted.
        const source = readFileSync(join(WEB_CLIENT_JS, 'features', 'vtt', 'vtt-core.js'), 'utf8');
        assert(
            /speakMessages/.test(source),
            'vtt-core.js no longer references VTT_CONFIG.speakMessages'
        );
        assert(
            /SpeechSynthesisUtterance/.test(source),
            'vtt-core.js no longer constructs a SpeechSynthesisUtterance -- the "Read aloud" chat feature may have been removed'
        );
    });

    it('both VTT chat panels (connected + local) expose the "Read aloud" checkbox', () => {
        for (const file of ['vtt-connected.js', 'vtt-local.js']) {
            const source = readFileSync(join(WEB_CLIENT_JS, 'features', 'vtt', file), 'utf8');
            assert(
                /id="vtt-speak-messages"/.test(source),
                `${file} is missing the #vtt-speak-messages checkbox`
            );
        }
    });
});
